### ISSUE TITLE
 `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by H7ioo** [Loskir/styled-qr-code#5]
Trying to upload Next.js app to Vercel. I'm getting this error:
```
Error: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /vercel/path0/node_modules/skia-canvas/lib/v6/index.node)
22:17:07.555

```
I tried to change node versions, 16 and 18 and it still doesn't work. Is there anything we can do?

**Comment by sa-od** [comment]
Is this issue resolved

`skia-canvas` is shared library of @loskir/styled-qr-code-node
it will only support with giblic 2.28 or later.

**Comment by H7ioo** [comment]
> Is this issue resolved
> 
> `skia-canvas` is shared library of @loskir/styled-qr-code-node
> it will only support with giblic 2.28 or later.

I lazy imported it instead.
