### ISSUE TITLE
Issue with skia-canvas versions < 1.0.2: Please bump to version 1.0.2

### ISSUE THREAD

**Issue by eliaskalapanidas** [Loskir/styled-qr-code#8]
As reported here [skia-version repo issue](https://github.com/samizdatco/skia-canvas/issues/160) there is a need to update skia-canvas dependency to the latest version 1.0.2 otherwise pre-compiled files will not be able to be discovered in their Aws S3 bucket, since they terminated their use due to rising costs and the builds will fail.

**Comment by zabdalimov** [comment]
We encountered this issue today and didn't want to wait until `skia-canvas` is upgraded in `styled-qr-code` so as a workaround we manually bumped its version in `yarn.lock` file of our workspaces project.

Before:
```
skia-canvas@^1.0.0:
  version "1.0.1"
  resolved "https://registry.npmjs.org/skia-canvas/-/skia-canvas-1.0.1.tgz#d0f6a4c99f273bb79311afa6e4410e09d5bb61b5"
  integrity sha512-/HtZlmib2BD3Fi6P4ZywSq7VquPl2A1Frc0pA+xD5hJSvSzN7FoOJpBWDpDd0e1ByzrVO6ZIjO98dNSQ2XqlKw==
  dependencies:
    "@mapbox/node-pre-gyp" "^1.0.9"
    cargo-cp-artifact "^0.1"
    glob "^8.0.3"
    path-browserify "^1.0.1"
    simple-get "^4.0.1"
    string-split-by "^1.0.0"
```

After:
```
skia-canvas@^1.0.0:
  version "1.0.2"
  resolved "https://registry.npmjs.org/skia-canvas/-/skia-canvas-1.0.2.tgz#00d2d1b0554c31c96b7e70cf1c72c01190d0c758"
  integrity sha512-9IjebOdBf6ir5Ktq0aM0wPshZ61oNX+T+2/ZBNJQZ63Z3SsSAd7i6YaYbqqtP6X8bK9mqB8QO1Y5DUZXNXuYHw==
  dependencies:
    "@mapbox/node-pre-gyp" "^1.0.9"
    cargo-cp-artifact "^0.1"
    glob "^8.0.3"
    path-browserify "^1.0.1"
    simple-get "^4.0.1"
    string-split-by "^1.0.0"
```

Manually editing lock files is of course not recommended, so use this at your own risk. I could image same could be done with npm and pnpm lock files.

**Comment by CharnSrinivas** [comment]
Please bump the version,

**Comment by CharnSrinivas** [comment]
> We encountered this issue today and didn't want to wait until `skia-canvas` is upgraded in `styled-qr-code` so as a workaround we manually bumped its version in `yarn.lock` file of our workspaces project.
> 
> Before:
> 
> ```
> skia-canvas@^1.0.0:
>   version "1.0.1"
>   resolved "https://registry.npmjs.org/skia-canvas/-/skia-canvas-1.0.1.tgz#d0f6a4c99f273bb79311afa6e4410e09d5bb61b5"
>   integrity sha512-/HtZlmib2BD3Fi6P4ZywSq7VquPl2A1Frc0pA+xD5hJSvSzN7FoOJpBWDpDd0e1ByzrVO6ZIjO98dNSQ2XqlKw==
>   dependencies:
>     "@mapbox/node-pre-gyp" "^1.0.9"
>     cargo-cp-artifact "^0.1"
>     glob "^8.0.3"
>     path-browserify "^1.0.1"
>     simple-get "^4.0.1"
>     string-split-by "^1.0.0"
> ```
> 
> After:
> 
> ```
> skia-canvas@^1.0.0:
>   version "1.0.2"
>   resolved "https://registry.npmjs.org/skia-canvas/-/skia-canvas-1.0.2.tgz#00d2d1b0554c31c96b7e70cf1c72c01190d0c758"
>   integrity sha512-9IjebOdBf6ir5Ktq0aM0wPshZ61oNX+T+2/ZBNJQZ63Z3SsSAd7i6YaYbqqtP6X8bK9mqB8QO1Y5DUZXNXuYHw==
>   dependencies:
>     "@mapbox/node-pre-gyp" "^1.0.9"
>     cargo-cp-artifact "^0.1"
>     glob "^8.0.3"
>     path-browserify "^1.0.1"
>     simple-get "^4.0.1"
>     string-split-by "^1.0.0"
> ```
> 
> Manually editing lock files is of course not recommended, so use this at your own risk. I could image same could be done with npm and pnpm lock files.

This worked for me but of course we need permanent solution

**Comment by brandonhudson** [comment]
I've tested a manual workaround for the time being by installing skia-canvas 1.0.2 directly into my project and saw no issues with performance or build errors.

`npm install skia-canvas@1.0.2`

**Comment by zabdalimov** [comment]
Opened PR https://github.com/Loskir/styled-qr-code/pull/9 to bump `skia-canvas` version.

@Loskir if you would have some spare time, please take a look and merge if everything is good from your side.

Thank you for this awesome fork you created!

**Comment by Loskir** [comment]
Hello! Thank you all for your interest

Version 1.5.2 with bumped version is published https://www.npmjs.com/package/@loskir/styled-qr-code-node
